In [1]:
import pandas as pd

In [2]:
import pandas as pd
df = pd.read_csv('student_dropout_dataset_v3.csv')
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [3]:
df.isnull()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
df.count()

Student_ID               10000
Age                      10000
Gender                   10000
Family_Income             9500
Internet_Access          10000
Study_Hours_per_Day       9500
Attendance_Rate          10000
Assignment_Delay_Days    10000
Travel_Time_Minutes      10000
Part_Time_Job            10000
Scholarship              10000
Stress_Index              9500
GPA                      10000
Semester_GPA             10000
CGPA                     10000
Semester                 10000
Department               10000
Parental_Education        9489
Dropout                  10000
dtype: int64

In [5]:
df.describe

<bound method NDFrame.describe of       Student_ID   Age  Gender  Family_Income Internet_Access  \
0              1  22.1    Male        25000.0             Yes
1              2  20.7    Male        25000.0             Yes
2              3  22.4    Male        40183.0             Yes
3              4  24.4    Male            NaN             Yes
4              5  20.5  Female        25319.0             Yes
...          ...   ...     ...            ...             ...
9995        9996  23.9  Female        42286.0              No
9996        9997  17.0  Female        61103.0             Yes
9997        9998  19.4    Male        25000.0             Yes
9998        9999  22.1  Female        40302.0             Yes
9999       10000  22.4  Female        76796.0             Yes

      Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  \
0                    3.36             86.1                      2
1                    4.30             68.0                      2
2                    4.40             70.9                      0
3                     NaN             82.2                      2
4                    4.19             75.7                      1
...                   ...              ...                    ...
9995                 4.62             92.0                      0
9996                 2.87             75.2                      3
9997                 4.73             74.9                      4
9998                 5.85             74.2                      1
9999                 4.95             83.7                      1

      Travel_Time_Minutes Part_Time_Job Scholarship  Stress_Index   GPA  \
0                    20.4           Yes          No           5.5  0.96
1                    44.0            No          No           6.8  1.28
2                    48.9           Yes          No           5.5  1.68
3                    38.6            No          No           NaN  1.78
4                    23.0            No          No           7.0  1.48
...                   ...           ...         ...           ...   ...
9995                 10.0           Yes         Yes           5.5  1.60
9996                 32.4            No         Yes           6.7  3.09
9997                 25.4            No          No           3.5  3.45
9998                  5.0            No         Yes           6.2  3.35
9999                 15.5           Yes          No           7.9  2.17

      Semester_GPA  CGPA Semester   Department Parental_Education  Dropout
0             0.90  0.90   Year 1         Arts        High School        0
1             1.20  1.19   Year 3  Engineering           Bachelor        1
2             1.32  1.32   Year 1         Arts             Master        0
3             1.77  1.77   Year 1           CS        High School        1
4             0.91  0.87   Year 4     Business           Bachelor        0
...            ...   ...      ...          ...                ...      ...
9995          0.99  0.97   Year 2         Arts           Bachelor        0
9996          3.09  3.09   Year 1     Business             Master        1
9997          3.37  3.43   Year 4     Business           Bachelor        0
9998          3.34  3.34   Year 1           CS        High School        0
9999          2.20  2.20   Year 1         Arts             Master        0

[10000 rows x 19 columns]>

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  str
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  str
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  str
 10  Scholarship            10000 non-null  str
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  str
 16  Department             10000 non-null  str
 17  Parental_Education     9489 non-null   str
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), str(7)
memory usage: 1.4 MB

In [7]:
df.isnull().sum()

Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  str
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  str
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  str
 10  Scholarship            10000 non-null  str
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  str
 16  Department             10000 non-null  str
 17  Parental_Education     9489 non-null   str
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), str(7)
memory usage: 1.4 MB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  str
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  str
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  str
 10  Scholarship            10000 non-null  str
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  str
 16  Department             10000 non-null  str
 17  Parental_Education     9489 non-null   str
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), str(7)
memory usage: 1.4 MB

In [10]:
df.value_counts()

Student_ID  Age   Gender  Family_Income  Internet_Access  Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  Travel_Time_Minutes  Part_Time_Job  Scholarship  Stress_Index  GPA   Semester_GPA  CGPA  Semester  Department   Parental_Education  Dropout
1           22.1  Male    25000.0        Yes              3.36                 86.1             2                      20.4                 Yes            No           5.5           0.96  0.90          0.90  Year 1    Arts         High School         0          1
2           20.7  Male    25000.0        Yes              4.30                 68.0             2                      44.0                 No             No           6.8           1.28  1.20          1.19  Year 3    Engineering  Bachelor            1          1
3           22.4  Male    40183.0        Yes              4.40                 70.9             0                      48.9                 Yes            No           5.5           1.68  1.32          1.32  Year 1    Arts         Master              0          1
5           20.5  Female  25319.0        Yes              4.19                 75.7             1                      23.0                 No             No           7.0           1.48  0.91          0.87  Year 4    Business     Bachelor            0          1
7           24.5  Male    25000.0        Yes              3.00                 78.2             1                      37.4                 Yes            Yes          7.3           0.64  0.33          0.44  Year 4    CS           Bachelor            0          1
                                                                                                                                                                                                                                                                     ..
9996        23.9  Female  42286.0        No               4.62                 92.0             0                      10.0                 Yes            Yes          5.5           1.60  0.99          0.97  Year 2    Arts         Bachelor            0          1
9997        17.0  Female  61103.0        Yes              2.87                 75.2             3                      32.4                 No             Yes          6.7           3.09  3.09          3.09  Year 1    Business     Master              1          1
9998        19.4  Male    25000.0        Yes              4.73                 74.9             4                      25.4                 No             No           3.5           3.45  3.37          3.43  Year 4    Business     Bachelor            0          1
9999        22.1  Female  40302.0        Yes              5.85                 74.2             1                      5.0                  No             Yes          6.2           3.35  3.34          3.34  Year 1    CS           High School         0          1
10000       22.4  Female  76796.0        Yes              4.95                 83.7             1                      15.5                 Yes            No           7.9           2.17  2.20          2.20  Year 1    Arts         Master              0          1
Name: count, Length: 9020, dtype: int64

In [11]:
df.describe()

,Student_ID,Age,Family_Income,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Stress_Index,GPA,Semester_GPA,CGPA,Dropout
count,10000.00000,10000.00000,9500.000000,9500.000000,10000.00000,10000.000000,10000.00000,9500.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,21.02606,38377.247474,4.014592,81.73683,1.799700,30.17926,5.507147,2.308440,2.300057,2.298761,0.23540
std,2886.89568,2.13981,20496.232179,1.295450,8.22093,1.344307,11.91887,1.765951,1.061717,1.074407,1.072555,0.42427
min,1.00000,17.00000,25000.000000,0.500000,38.20000,0.000000,5.00000,1.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,19.50000,25000.000000,3.160000,76.40000,1.000000,21.90000,4.300000,1.550000,1.520000,1.520000,0.00000
50%,5000.50000,21.00000,29740.500000,4.000000,81.80000,2.000000,30.20000,5.500000,2.350000,2.350000,2.350000,0.00000
75%,7500.25000,22.50000,44520.000000,4.870000,87.30000,3.000000,38.40000,6.700000,3.120000,3.150000,3.150000,0.00000
max,10000.00000,29.60000,316601.000000,8.980000,100.00000,8.000000,74.90000,10.000000,4.000000,4.000000,4.000000,1.00000

In [12]:
df.shape

(10000, 19)

In [13]:
df.isnull()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [15]:
df.mean

<bound method DataFrame.mean of       Student_ID   Age  Gender  Family_Income Internet_Access  \
0              1  22.1    Male        25000.0             Yes
1              2  20.7    Male        25000.0             Yes
2              3  22.4    Male        40183.0             Yes
3              4  24.4    Male            NaN             Yes
4              5  20.5  Female        25319.0             Yes
...          ...   ...     ...            ...             ...
9995        9996  23.9  Female        42286.0              No
9996        9997  17.0  Female        61103.0             Yes
9997        9998  19.4    Male        25000.0             Yes
9998        9999  22.1  Female        40302.0             Yes
9999       10000  22.4  Female        76796.0             Yes

      Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  \
0                    3.36             86.1                      2
1                    4.30             68.0                      2
2                    4.40             70.9                      0
3                     NaN             82.2                      2
4                    4.19             75.7                      1
...                   ...              ...                    ...
9995                 4.62             92.0                      0
9996                 2.87             75.2                      3
9997                 4.73             74.9                      4
9998                 5.85             74.2                      1
9999                 4.95             83.7                      1

      Travel_Time_Minutes Part_Time_Job Scholarship  Stress_Index   GPA  \
0                    20.4           Yes          No           5.5  0.96
1                    44.0            No          No           6.8  1.28
2                    48.9           Yes          No           5.5  1.68
3                    38.6            No          No           NaN  1.78
4                    23.0            No          No           7.0  1.48
...                   ...           ...         ...           ...   ...
9995                 10.0           Yes         Yes           5.5  1.60
9996                 32.4            No         Yes           6.7  3.09
9997                 25.4            No          No           3.5  3.45
9998                  5.0            No         Yes           6.2  3.35
9999                 15.5           Yes          No           7.9  2.17

      Semester_GPA  CGPA Semester   Department Parental_Education  Dropout
0             0.90  0.90   Year 1         Arts        High School        0
1             1.20  1.19   Year 3  Engineering           Bachelor        1
2             1.32  1.32   Year 1         Arts             Master        0
3             1.77  1.77   Year 1           CS        High School        1
4             0.91  0.87   Year 4     Business           Bachelor        0
...            ...   ...      ...          ...                ...      ...
9995          0.99  0.97   Year 2         Arts           Bachelor        0
9996          3.09  3.09   Year 1     Business             Master        1
9997          3.37  3.43   Year 4     Business           Bachelor        0
9998          3.34  3.34   Year 1           CS        High School        0
9999          2.20  2.20   Year 1         Arts             Master        0

[10000 rows x 19 columns]>

In [17]:
df.isnull().sum()

Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [46]:
df.fillna(df['Family_Income'].mean(), inplace=True)
df.fillna(df['Study_Hours_per_Day'].median(), inplace=True)
df.fillna(df['Stress_Index'].mean(), inplace=True)
df.fillna(df['Parental_Education'].mode()[0], inplace=True)

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,1,25000.000000,1,3.360000,86.1,2,20.4,1,0,5.500000,0.96,0.90,0.90,0,0,1,0
1,2,20.7,1,25000.000000,1,4.300000,68.0,2,44.0,0,0,6.800000,1.28,1.20,1.19,2,3,0,1
2,3,22.4,1,40183.000000,1,4.400000,70.9,0,48.9,1,0,5.500000,1.68,1.32,1.32,0,0,2,0
3,4,24.4,1,38377.247474,1,38377.247474,82.2,2,38.6,0,0,38377.247474,1.78,1.77,1.77,0,2,1,1
4,5,20.5,0,25319.000000,1,4.190000,75.7,1,23.0,0,0,7.000000,1.48,0.91,0.87,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.9,0,42286.000000,0,4.620000,92.0,0,10.0,1,1,5.500000,1.60,0.99,0.97,1,0,0,0
9996,9997,17.0,0,61103.000000,1,2.870000,75.2,3,32.4,0,1,6.700000,3.09,3.09,3.09,0,1,2,1
9997,9998,19.4,1,25000.000000,1,4.730000,74.9,4,25.4,0,0,3.500000,3.45,3.37,3.43,3,1,0,0
9998,9999,22.1,0,40302.000000,1,5.850000,74.2,1,5.0,0,1,6.200000,3.35,3.34,3.34,0,2,1,0
9999,10000,22.4,0,76796.000000,1,4.950000,83.7,1,15.5,1,0,7.900000,2.17,2.20,2.20,0,0,2,0

In [47]:
df.isnull().sum()

Student_ID               0
Age                      0
Gender                   0
Family_Income            0
Internet_Access          0
Study_Hours_per_Day      0
Attendance_Rate          0
Assignment_Delay_Days    0
Travel_Time_Minutes      0
Part_Time_Job            0
Scholarship              0
Stress_Index             0
GPA                      0
Semester_GPA             0
CGPA                     0
Semester                 0
Department               0
Parental_Education       0
Dropout                  0
dtype: int64

In [48]:
df.fillna(2)

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,1,25000.000000,1,3.360000,86.1,2,20.4,1,0,5.500000,0.96,0.90,0.90,0,0,1,0
1,2,20.7,1,25000.000000,1,4.300000,68.0,2,44.0,0,0,6.800000,1.28,1.20,1.19,2,3,0,1
2,3,22.4,1,40183.000000,1,4.400000,70.9,0,48.9,1,0,5.500000,1.68,1.32,1.32,0,0,2,0
3,4,24.4,1,38377.247474,1,38377.247474,82.2,2,38.6,0,0,38377.247474,1.78,1.77,1.77,0,2,1,1
4,5,20.5,0,25319.000000,1,4.190000,75.7,1,23.0,0,0,7.000000,1.48,0.91,0.87,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.9,0,42286.000000,0,4.620000,92.0,0,10.0,1,1,5.500000,1.60,0.99,0.97,1,0,0,0
9996,9997,17.0,0,61103.000000,1,2.870000,75.2,3,32.4,0,1,6.700000,3.09,3.09,3.09,0,1,2,1
9997,9998,19.4,1,25000.000000,1,4.730000,74.9,4,25.4,0,0,3.500000,3.45,3.37,3.43,3,1,0,0
9998,9999,22.1,0,40302.000000,1,5.850000,74.2,1,5.0,0,1,6.200000,3.35,3.34,3.34,0,2,1,0
9999,10000,22.4,0,76796.000000,1,4.950000,83.7,1,15.5,1,0,7.900000,2.17,2.20,2.20,0,0,2,0

In [49]:
df.isnull().sum()

Student_ID               0
Age                      0
Gender                   0
Family_Income            0
Internet_Access          0
Study_Hours_per_Day      0
Attendance_Rate          0
Assignment_Delay_Days    0
Travel_Time_Minutes      0
Part_Time_Job            0
Scholarship              0
Stress_Index             0
GPA                      0
Semester_GPA             0
CGPA                     0
Semester                 0
Department               0
Parental_Education       0
Dropout                  0
dtype: int64

In [50]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols = ['Gender','Internet_Access','Part_Time_Job',
        'Scholarship','Semester','Department',
        'Parental_Education']

for col in cols:
    df[col] = le.fit_transform(df[col])

In [51]:
X = df[['Student_ID','Age','Gender','Family_Income',
        'Internet_Access','Study_Hours_per_Day',
        'Attendance_Rate','Assignment_Delay_Days',
        'Travel_Time_Minutes','Part_Time_Job',
        'Scholarship','Stress_Index','GPA',
        'Semester_GPA','CGPA','Semester',
        'Department','Parental_Education']]

y = df['Dropout']

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [54]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [55]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7995

In [56]:
from sklearn.cluster import KMeans

cluster_model = KMeans(n_clusters=3, random_state=42)
cluster_model.fit(X)

KMeans(n_clusters=3, random_state=42)

In [58]:
import joblib
joblib.dump(model, "dropout_model.pkl")
joblib.dump(cluster_model, "cluster_model.pkl")

['cluster_model.pkl']